In [1]:
import numpy as np 

**(1)** Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [2]:
squaremeter = [60, 65, 80, 85, 70, 65, 105, 90, 80, 75]
rooms = [1, 2, 2, 3, 2, 1, 3, 3, 2, 2]
price = [500000, 550000, 750000, 900000, 650000, 600000, 1000000, 900000, 775000, 675000]

houses = np.array([squaremeter, rooms, price])
houses

array([[     60,      65,      80,      85,      70,      65,     105,
             90,      80,      75],
       [      1,       2,       2,       3,       2,       1,       3,
              3,       2,       2],
       [ 500000,  550000,  750000,  900000,  650000,  600000, 1000000,
         900000,  775000,  675000]])

**(2)** Transpose the array you have created, so that every line can represent features of one house.

In [3]:
houses.T

array([[     60,       1,  500000],
       [     65,       2,  550000],
       [     80,       2,  750000],
       [     85,       3,  900000],
       [     70,       2,  650000],
       [     65,       1,  600000],
       [    105,       3, 1000000],
       [     90,       3,  900000],
       [     80,       2,  775000],
       [     75,       2,  675000]])

**(3)** Display the shape of the array and explain what it means.

In [4]:
print(f"The array contains {houses.shape[0]} rows and {houses.shape[1]} columns")

The array contains 3 rows and 10 columns


**(4)** Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [5]:
def ones_zeros():
    row = int(input("Enter the row number:"))
    column = int(input("Enter the columns number:"))
    array = np.ones((row, column))
    array[1:row:2, 1:column:2] = 0
    return array

ones_zeros()

Enter the row number: 6
Enter the columns number: 5


array([[1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.]])